# The following redirect is intended for use with most SPAs that handle
# routing internally.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = ""
  to = ""
  status = 200
  focre = true
  headers = {Access-Control-Allow-Origin = "*"}

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"

[build]
  functions = "lambda"
  Command = "yarn prod"
  publish = "build"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"